name: Build App

on: 
  pull_request:
  push:
    branches: [development]
    

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - run: npm install
    - run: node app.js

