name: Build App

on: 
  pull_request:
  push:
    branches: [development]
    

jobs:
  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Create Node Environment
      uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
    - name: NPM Install
      run: npm ci
    - name: Test
      run: npm test


